extends: "airbnb"
rules:
    indent: ["error", 4]
    react/jsx-indent: ["error", 4]
    react/jsx-filename-extension: [0]
    class-methods-use-this: [0]
    react/prefer-stateless-function: [0]
    import/no-extraneous-dependencies: [0]
env:
    browser: true
globals:
    atom: true
